### ISSUE TITLE
Get familiar with docker-scripts

### ISSUE THREAD

**Issue by dashohoxha** [docker-scripts/freedombox#1]
1. Read the README, man-page and wiki:
    - https://github.com/docker-scripts/ds#dockerscripts
    - https://docker-scripts.github.io/ds/man/
    - https://github.com/docker-scripts/ds/wiki

2. Read the code of docker-scripts and try to understand how it works. Use a bash guide for things that you don't understand (actually it is better to finish reading the bash guide before studying the code).
    - https://github.com/docker-scripts/ds/tree/master/sh
    - https://en.wikibooks.org/wiki/Bash_Shell_Scripting

3. Install and test several docker-scripts applications, then study their code as well, to see how they are implemented:
    - https://github.com/docker-scripts/monit
    - https://github.com/docker-scripts/shellinabox
    - https://github.com/docker-scripts/schooltool
    - https://github.com/docker-scripts/squid
    - https://github.com/docker-scripts/bind9
    - https://github.com/docker-scripts/moodle
    - https://github.com/docker-scripts/mariadb
    - https://github.com/docker-scripts/dbox
 
@docker-scripts/ds

**Comment by RadZaeem** [comment]
I have done 1., 2. and several apps for 3.

**Comment by dashohoxha** [comment]
Please test and study all the apps listed on 3.

**Comment by RadZaeem** [comment]
OK will do it
