### ISSUE TITLE
Fix Dockerfile

### ISSUE THREAD

**Issue by dashohoxha** [docker-scripts/freedombox#11]
Why `FROM debian:buster`? https://github.com/docker-scripts/freedombox/blob/master/Dockerfile#L1
Why not `FROM debian:stretch`? I think that we should work with the latest stable version first, and after this is done we may also try the testing version.
@SunilMohanAdapa what is your opinion on this?

**Comment by dashohoxha** [comment]
Don't install the package `dialog`:
https://github.com/docker-scripts/freedombox/blob/master/Dockerfile#L7

I think it is for interactive questions, and this is not OK with Docker. Building an image should not ask any questions to the user. For this reason we use: `DEBIAN_FRONTEND=noninteractive apt -y install ...` There is even a commented example on the Dockerfile.
I don't know about `apt-utils` but I suspect it is also for interactive installation.

Please remove this line and fix any problems with `DEBIAN_FRONTEND=noninteractive`.

**Comment by dashohoxha** [comment]
I think `apt -y upgrade` is needed:
https://github.com/docker-scripts/freedombox/blob/master/Dockerfile#L8

**Comment by RadZaeem** [comment]
- I skip apt upgrade until we achieve stable version of container. Because I rebuild many times.
- Debian stable version is old version of Freedombox. Many things changed in testing. Stable version has limitations like requiring restart, requiring running first-run setup and so on, plinth is tightly integrated with main freedombox an so on
  - Wait for @SunilMohanAdapa for this his opinion.

**Comment by dashohoxha** [comment]
> I skip apt upgrade until we achieve stable version of container. Because I rebuild many times.

I think that you have missed my point. Look at line 8 of Dockerfile.

> Debian stable version is old version of Freedombox.

It is not an old version of FreedomBox, it is the stable version. The aim of this project is to build a container for the latest stable version of FreedomBox (and Debian).

Then you should also build a development version, with the latest version of FreedomBox and Debian, getting Plinth from a git repository, etc. You will need this development version to do the coding, while adding CLI features to plinth.

It doesn't hurt to do both of them, so there is no need to wait for the opinion of @SunilMohanAdapa

**Comment by RadZaeem** [comment]
OK please give me time to rewrite everything for stable.
Freedombox stable requires restart, run setup and restart again, if installed on normal Debian. I am not sure how I would deal with it with Docker.

**Comment by dashohoxha** [comment]
> OK give me time to rewrite everything for stable.

Also don't forget to move the current version to the branch `dev`. Do you know how to do it, or do you need some help?
Alternatively, keep the development branch on `master`, and create another branch called `stable` for the stable version. Whichever you prefer.

You have plenty of time available. Actually you are going quickly and you are ahead of time (but at the expense of not being careful and not being very good with the quality, in my opinion).

> Just asking , do we really need to use Freedombox from Debian stable. Despite in testing, the testing version has many bug fixes and improvements (UI, apps management, etc.). I tried both of them and the stable version feels like alpha or beta version of Freedombox.

We don't have to worry about that. It is up to the FreedomBox developers and packagers to decide what should go on the stable version. Maybe later they will release a new version of the package that includes the latest improvements. And of course they will do this after they test everything and make sure that there are no problems. This is why it is called stable. It is OK if a stable release is a bit outdated, as long as it offers assurance to the users that there are no problems.
